sonar.projectKey=proyecto-login-qa
sonar.projectName=Proyecto Login QA
sonar.sources=app,pages
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8
